version: "2"
linters:
  default: all
  disable:
    - depguard
    - cyclop
    - noinlineerr
    - nlreturn
    - revive
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    varnamelen:
      ignore-names:
        - i, j, fn, in, tt
        - x, sb
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustruct
          - funlen
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/devemio/docker-color-output)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
