version: "2"
linters:
  default: all
  disable:
    - depguard
    - noinlineerr
    - nlreturn
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 20
    revive:
      rules:
        - name: blank-imports
        - name: context-keys-type
        - name: error-strings
        - name: if-return
        - name: receiver-naming
        - name: time-naming
        - name: var-declaration
    varnamelen:
      ignore-names:
        - i, j, fn, in, tt
        - x, sb
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustruct
          - funlen
        path: (.+)_test\.go
      - linters:
          - wrapcheck
        text: gopkg\.in/yaml\.v3\.Unmarshal
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
